"""coherax -- Coherent-basis optimization for bosonic quantum codes.

Public API is organized into submodules:

- :mod:`coherax.linalg_utils` -- Pure-JAX math primitives (GKP_N, coherent-state kernels, sparse eigh)
- :mod:`coherax._fock` -- Dynamiqs glue, Fock-basis constants, Kraus-channel utilities (transitional)
- :mod:`coherax.states` -- Ket/DM hierarchy and typed basis-defined operators
- :mod:`coherax.circuits` -- CD+R circuit construction, TraceoutLayer, ``g()``
- :mod:`coherax.fidelity` -- Analytic fidelity computations
- :mod:`coherax.gkp` -- GKP code state generators
- :mod:`coherax.optimizers` -- ECD circuit optimization
"""

from coherax.linalg_utils import (
    GKP_N,
    aOmegab,
    coherent_overlap,
    complex_normal,
    dag,
    e_n1iaOmegab,
    invsqrtm_supp,
    sparse_eigh,
    sparse_tensor_eigh,
)
from coherax._fock import (
    IN,
    I2,
    a_op,
    a_dag_op,
    apply_kraus_map,
    apply_kraus_map_n,
    apply_kraus_map_nonorm,
    compose_channel_kraus,
    dqcoherent,
    dqcoherent_dm,
    dqcreate,
    dqdag,
    dqdestroy,
    dqdisplace,
    dqeye,
    dqexpect,
    dqfock_dm,
    dqnumber,
    dqptrace,
    dqsqueeze,
    dqtensor,
    dqtodm,
    dqtrace,
    ket0,
    ket1,
    make_pureloss_fock,
    make_thermalloss_fock,
    make_transpose_for_pureloss,
    n_hat,
    p_quad,
    root2,
    sigma_x,
    sigma_y,
    sigma_z,
    von_neumann_entropy,
    x_quad,
)

from coherax.states import (
    BosonicSubspace,
    CPTP,
    CoherentCoherentOp,
    CoherentDM,
    CoherentFockOp,
    CoherentKet,
    DM,
    Displacer,
    FockCoherentOp,
    FockDM,
    FockFockOp,
    FockKet,
    JointKet,
    Ket,
    LogicalKet,
    QubitKet,
    Rotator,
    beamsplit_full,
    encode_logical_ket,
    encode_logical_kets,
    unitary_encoding_map,
)

from coherax.circuits import (
    CD,
    CircuitUnitary,
    ECD,
    R_x,
    R_y,
    R_z,
    TraceoutLayer,
    W,
    channel_from_b,
    circuit_layer,
    circuit_params_to_2channel,
    circuit_params_to_time,
    compose_ECD_layers,
    ecd_rotation_2x2,
    g,
    gate_timer,
    qubit_rotation,
    super_g,
    traceout_unitary,
)

from coherax.fidelity import (
    coherent_information_pureloss,
    entanglement_fidelity_pureloss,
    nbar_logical,
    analytic_fidelity,
    analytic_fidelity_i,
    analytic_fidelity_transfer,
    analytic_fidelity_transfer_i,
    analytic_fidelity_fock_state,
    analytic_fidelity_wrapper,
    analytic_fidelity_transfer_wrapper,
    analytic_fidelity_fock_wrapper,
    state_fidelity,
    circuit_state_fidelity,
    circuit_fock_fidelity,
)

from coherax.gkp import (
    gkp_coherent_dm,
)

from coherax.optimizers import (
    init_separated_d,
    optimize_ECD_state_prep,
    optimize_ECD_state_transfer,
    optimize_Fe_floating,
    optimize_Ic_floating,
    separation_penalty,
)

__all__ = [
    # operators
    "GKP_N",
    "IN",
    "I2",
    "root2",
    "sigma_x",
    "sigma_y",
    "sigma_z",
    "n_hat",
    "a_op",
    "a_dag_op",
    "x_quad",
    "p_quad",
    "ket0",
    "ket1",
    "aOmegab",
    "e_n1iaOmegab",
    "coherent_overlap",
    "complex_normal",
    "dag",
    "invsqrtm_supp",
    "sparse_eigh",
    "sparse_tensor_eigh",
    "dqtensor",
    "dqdag",
    "dqeye",
    "dqnumber",
    "dqdestroy",
    "dqcreate",
    "dqtrace",
    "dqdisplace",
    "dqsqueeze",
    "dqfock_dm",
    "dqcoherent_dm",
    "dqcoherent",
    "dqptrace",
    "dqexpect",
    "dqtodm",
    "apply_kraus_map",
    "apply_kraus_map_n",
    "apply_kraus_map_nonorm",
    "compose_channel_kraus",
    "make_pureloss_fock",
    "make_thermalloss_fock",
    "make_transpose_for_pureloss",
    "von_neumann_entropy",
    # states
    "Ket",
    "DM",
    "CoherentKet",
    "CoherentDM",
    "FockKet",
    "FockDM",
    "CoherentCoherentOp",
    "FockFockOp",
    "CoherentFockOp",
    "FockCoherentOp",
    "Displacer",
    "Rotator",
    "CPTP",
    "QubitKet",
    "LogicalKet",
    "JointKet",
    "BosonicSubspace",
    "beamsplit_full",
    "encode_logical_ket",
    "encode_logical_kets",
    "unitary_encoding_map",
    # circuits
    "W",
    "CD",
    "CircuitUnitary",
    "ECD",
    "R_x",
    "R_y",
    "R_z",
    "qubit_rotation",
    "ecd_rotation_2x2",
    "circuit_layer",
    "compose_ECD_layers",
    "traceout_unitary",
    "circuit_params_to_2channel",
    "TraceoutLayer",
    "g",
    "channel_from_b",
    "super_g",
    "gate_timer",
    "circuit_params_to_time",
    # fidelity
    "analytic_fidelity",
    "analytic_fidelity_i",
    "analytic_fidelity_transfer",
    "analytic_fidelity_transfer_i",
    "analytic_fidelity_fock_state",
    "analytic_fidelity_wrapper",
    "analytic_fidelity_transfer_wrapper",
    "analytic_fidelity_fock_wrapper",
    "state_fidelity",
    "circuit_state_fidelity",
    "circuit_fock_fidelity",
    "coherent_information_pureloss",
    "entanglement_fidelity_pureloss",
    "nbar_logical",
    # gkp
    "gkp_coherent_dm",
    # optimizers
    "optimize_ECD_state_prep",
    "optimize_ECD_state_transfer",
    "optimize_Fe_floating",
    "optimize_Ic_floating",
    "init_separated_d",
    "separation_penalty",
]
